<?php

namespace App\Filament\Admin\Resources\OrderResource\RelationManagers;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class AgenciesRelationManager extends RelationManager
{
    protected static string $relationship = 'agencies';
protected static ?string $title="سلسلة التوكيل";
    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
protected function canEdit(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}
protected function canDelete(Model $record): bool
{
    return false ; // TODO: Change the autogenerated stub
}

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('task')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('task')
            ->columns([
                Tables\Columns\TextColumn::make('task')->label('وصف المهمة'),
                Tables\Columns\TextColumn::make('user.name')->label('الموظف'),
                Tables\Columns\TextColumn::make('activate')->label('حالة المهمة'),
                Tables\Columns\TextColumn::make('msg')->label('ملاحظات الموظف'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
