<?php

namespace App\Filament\Branch\Resources\UserResource\Pages;

use App\Filament\Branch\Resources\UserResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {


        while(true){
            $code=\Str::random(8);

            $user=User::where('num_id',$code)->first();
            if(!$user){
                $data['num_id']=$code;
                break;
            }
        }



        $data['phone'] = '+'.$data['country_code'] . $data['phone_number'];
        unset($data['country_code'], $data['phone_number']); // حذف الحقول المنفصلة بعد الجمع
        return $data;


//        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub



    }





    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

}
