<?php

namespace App\Filament\Employ\Resources;

use App\Enums\BalanceTypeEnum;
use App\Filament\Employ\Resources\BalabceTRResource\Pages;
use App\Filament\Employ\Resources\BalabceTRResource\RelationManagers;
use App\Helper\HelperBalance;
use App\Models\BalabceTR;
use App\Models\Balance;
use App\Models\Order;
use Closure;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class BalabceTRResource extends Resource
{
    protected static ?string $model = Balance::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $pluralModelLabel = 'الرصيد TRY';
    protected static ?string $navigationGroup = 'الرصيد';
    protected static ?string $label = 'الرصيد TRY';
    protected static ?string $navigationLabel = 'الرصيد TRY';

public static function canCreate(): bool
{
    return false; // TODO: Change the autogenerated stub
}

public static function canEdit(Model $record): bool
{
    return false;// TODO: Change the autogenerated stub
}
public static function canDelete(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}
public static function canDeleteAny(): bool
{
    return false; // TODO: Change the autogenerated stub
}

public static function canForceDelete(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}

public static function canView(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('سندات')->schema([
                    Forms\Components\Select::make('type')->options([
                        BalanceTypeEnum::CATCH->value => BalanceTypeEnum::CATCH->getLabel(),

                    ])->default(BalanceTypeEnum::CATCH->value)->live()
                        ->rules([
                            fn(): Closure => function (string $attribute, $value, Closure $fail) {
                                $validateArray = [
                                    BalanceTypeEnum::CATCH->value,
                                    // BalanceTypeEnum::PUSH->value,
                                ];
                                if (empty($value) || in_array($value, $validateArray)) {
                                    $fail('يجب إختيار نوع سند صحيح');
                                }
                            },
                        ])->required()->label('نوع السند'),
                    Forms\Components\TextInput::make('credit')->label('القيمة')->numeric()->visible(fn($get) => $get('type') === BalanceTypeEnum::PUSH->value)->required()
                        ->rules([
                            fn(): Closure => function (string $attribute, $value, Closure $fail) {
                                if ($value <= 0) {
                                    $fail('يجب أن تكون القيمة أكبر من 0');
                                }
                            },
                        ]),
                    Forms\Components\TextInput::make('debit')
                        ->label('القيمة')
                        ->numeric()
                        ->visible(fn($get) => $get('type') === BalanceTypeEnum::CATCH->value)
                        ->required()->rules([
                            fn(): Closure => function (string $attribute, $value, Closure $fail) {
                                if ($value <= 0) {
                                    $fail('يجب أن تكون القيمة أكبر من 0');
                                }
                            },
                        ]),
                    Forms\Components\Select::make('user_id')->options(function () {
                        $orders = auth()->user()->pendingBalances->pluck('order_id')->toArray();
                        return Order::whereIn('id', $orders)->pluck('id', 'code');
                    })->label('مرتبط بالطلب رقم'),
                    Forms\Components\TextInput::make('info')->label('ملاحظات'),
                    Forms\Components\TextInput::make('customer_name')->required()->label('اسم الزبون  المستلم')

                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn($query) => $query->where('user_id', auth()->id())->where('currency_id',2)->latest())
            ->columns([
                Tables\Columns\TextColumn::make('credit')->label('إيداع')->formatStateUsing(fn($state)=>HelperBalance::formatNumber($state)),
                Tables\Columns\TextColumn::make('debit')->label('قبض')->formatStateUsing(fn($state)=>HelperBalance::formatNumber($state)),
                Tables\Columns\TextColumn::make('customer_name')->label('اسم الزبون المستلم'),
                Tables\Columns\TextColumn::make('info')->label('الملاحظات'),
                Tables\Columns\TextColumn::make('customer_name')->label('الطرف المقابل'),
                Tables\Columns\TextColumn::make('order.code')->label('الطلب'),
                Tables\Columns\TextColumn::make('order.sender.name')->label('المرسل')->description(fn($record)=>$record->order?->general_sender_name!=null ? "{$record->order->general_sender_name}":""),
                Tables\Columns\TextColumn::make('order.receive.name')->label('المستلم')->description(fn($record)=>$record->order?->global_name!=null?" {$record->order->global_name}":""),

                Tables\Columns\TextColumn::make('total')->label('الرصيد')->formatStateUsing(fn($state)=>HelperBalance::formatNumber($state)),
                Tables\Columns\TextColumn::make('created_at')->date('Y-m')->label('التاريخ'),

            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('complete')->action(fn($record)=>$record->update(['is_complete'=>true]))->visible(fn($record)=>!$record->is_complete)
                    ->label('تأكيد إستلام الدفعة')->requiresConfirmation(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListBalabceTRS::route('/'),
            'create' => Pages\CreateBalabceTR::route('/create'),
            'edit' => Pages\EditBalabceTR::route('/{record}/edit'),
        ];
    }
}
