<?php

namespace App\Filament\Employ\Resources\BalabceTRResource\Pages;

use App\Filament\Employ\Resources\BalabceTRResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateBalabceTR extends CreateRecord
{
    protected static string $resource = BalabceTRResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();
        $data['code'] = \Str::uuid();

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
