<?php

namespace App\Filament\Branch\Resources\OrderResource\Pages;

use App\Enums\BayTypeEnum;
use App\Enums\LevelUserEnum;
use App\Enums\OrderStatusEnum;
use App\Filament\Branch\Resources\OrderResource;
use App\Helper\HelperBalance;
use App\Models\City;
use App\Models\Order;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {

        $city_source=City::find($data['city_source_id']);
        $city_target=City::find($data['city_target_id']);
        $data['code'] = "AWB" . now()->format('YmdHis'); // الطابع الزمني بتنسيق قصير
        $data['branch_source_id'] =$city_source->branch_id;
        $data['branch_target_id'] =$city_target->branch_id;
        $target=User::where('level',LevelUserEnum::BRANCH->value)->where('branch_id',$data['branch_target_id'] )->first();
      /*  $data['given_id']=$target?->id;
        $data['status']=OrderStatusEnum::TRANSFER->value;*/
       // $data['shipping_date'] = now()->format('Y-h-d');
       // $data['status'] = OrderStatusEnum::PENDING->value;
        $data['bay_type'] = BayTypeEnum::AFTER->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }


}
