<?php

namespace App\Filament\Employ\Resources\BalanceResource\Pages;

use App\Filament\Employ\Resources\BalanceResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateBalance extends CreateRecord
{
    protected static string $resource = BalanceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();
        $data['code'] = \Str::uuid();

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
