<?php

namespace App\Filament\Admin\Widgets;
use App\Enums\LevelUserEnum;
use App\Helper\HelperBalance;
use App\Models\Balance;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class BalanceCustomerView extends BaseWidget
{
    protected static ?string $pollingInterval = '10s';
    protected ?string $heading='إجمالي الأرصدة';
    protected int|string|array $columnSpan =4;
    public static function canView(): bool
    {
        ;
        return !\Str::endsWith(request()->fullUrl(),'admin') && !\Str::endsWith(request()->fullUrl(),'admin/') ; // TODO: Change the autogenerated stub
    }
    protected function getStats(): array
    {

        $totalUsd=Balance::
                whereHas('user',fn($query)=>$query->where('users.level',LevelUserEnum::USER->value))->selectRaw('SUM(credit - debit)as total')

        ->where('balances.is_complete', 1)
        ->where('balances.pending', '=',false)
        ->where('balances.currency_id', '=',1)->first();
        $totalTRY=Balance::
        whereHas('user',fn($query)=>$query->where('users.level',LevelUserEnum::USER->value))->selectRaw('SUM(credit - debit)as total')

            ->where('balances.is_complete', 1)
            ->where('balances.pending', '=',true)
            ->where('balances.currency_id', '=',2)->first();

        $pendingUsd=Balance::
        whereHas('user',fn($query)=>$query->where('users.level',LevelUserEnum::USER->value))->selectRaw('SUM(credit - debit)as total')

            ->where('balances.is_complete', 1)
            ->where('balances.pending', '=',true)
            ->where('balances.currency_id', '=',1)->first();
        $pendingTRY=Balance::
        whereHas('user',fn($query)=>$query->where('users.level',LevelUserEnum::USER->value))->selectRaw('SUM(credit - debit)as total')

            ->where('balances.is_complete', 1)
            ->where('balances.pending', '=',false)
            ->where('balances.currency_id', '=',2)->first();

      return [
          Stat::make('مجموع رصيد الزبائن USD ' , HelperBalance::formatNumber($totalUsd->total)),
          Stat::make('مجموع رصيد الزبائن TRY ' , HelperBalance::formatNumber($totalTRY->total)),
          Stat::make('مجموع رصيد قيد التحصيل USD ' , HelperBalance::formatNumber($pendingUsd->total)),
          Stat::make('مجموع رصيد قيد التحصيل TRY ' , HelperBalance::formatNumber($pendingTRY->total)),
      ];
    }
}
