<?php

namespace App\Filament\Admin\Widgets;

use App\Models\Order;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class DailyOverview extends BaseWidget
{
    protected ?string $heading='تقرير يومي';

    public static function canView(): bool
    {
        return auth()->user()->can('widget_DailyOverview'); // TODO: Change the autogenerated stub
    }

    protected function getStats(): array
    {
        $ordersNum=Order::whereDate('created_at',now());
        $senderFar=Order::whereDate('created_at',now())->where('orders.far_sender',1);
        $reciveFar=Order::whereDate('created_at',now())->where('orders.far_sender',0);
        return [
            Stat::make('الشحنات المنشأة اليوم', $ordersNum->count()),
            Stat::make('إجمالي قيمة الشحنات USD', $ordersNum->sum('price')),
            Stat::make('إجمالي قيمة الشحنات TRY', $ordersNum->sum('price_tr')),
            Stat::make('إجمالي أجور الشحنات USD  على المرسل', $senderFar->sum('far')),
            Stat::make('إجمالي أجور الشحنات USD  على المستلم',$reciveFar->sum('far')),
            Stat::make('إجمالي أجور الشحنات TRY  على المرسل', $senderFar->sum('far_tr')),
            Stat::make('إجمالي أجور الشحنات TRY  على المستلم', $reciveFar->sum('far_tr')),
        ];
    }
}
