<?php

namespace App\Filament\Admin\Resources\AccountStatmentStaffResource\Pages;

use App\Enums\LevelUserEnum;
use App\Filament\Admin\Resources\AccountStatmentStaffResource;
use Filament\Actions;
use Filament\Resources\Components\Tab;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListAccountStatmentStaff extends ListRecords
{
    protected static string $resource = AccountStatmentStaffResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function getTabs(): array
    {
        return [
            Tab::make('all')->modifyQueryUsing(fn($query)=>$query)->label('الكل'),
            Tab::make('usd')->modifyQueryUsing(fn($query)=>$query->where('currency_id',1))->label('USD'),
            Tab::make('try')->modifyQueryUsing(fn($query)=>$query->where('currency_id',2))->label('TRY'),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->whereHas('user',fn($query)=>$query
            ->where('level',LevelUserEnum::ADMIN->value)
            ->orWhere('level',LevelUserEnum::STAFF->value)
            ->orWhere('level',LevelUserEnum::BRANCH->value)

        )->where('is_complete',1)->latest(); // TODO: Change the autogenerated stub
    }
}
