<?php

namespace App\Filament\Admin\Resources\UserResource\RelationManagers;

use App\Models\Balance;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PendingBalancesRelationManager extends RelationManager
{
    protected static string $relationship = 'pendingBalances';

    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('total')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('total')
            ->columns([
                Tables\Columns\TextColumn::make('credit')->label('إيداع'),
                Tables\Columns\TextColumn::make('debit')->label('سحب'),
                Tables\Columns\TextColumn::make('total')->label('الرصيد'),
                Tables\Columns\TextColumn::make('info')->label('البيان'),
                Tables\Columns\TextColumn::make('order.code')->label('رقم الطلب'),
                Tables\Columns\TextColumn::make('created_at')->date('Y-m-d')->label('تاريخ العملية'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
                Tables\Actions\Action::make('complete')->action(function($record){
                    \DB::beginTransaction();
                    try{
                        Balance::create([
                            'credit'=>$record->debit,
                            'debit'=>0,
                            'total'=>$record->user?->total_balance+$record->debit,
                            'info'=>'تم إستلام المبلغ للطلب رقم : '.$record->order?->code,
                            'order_id'=>$record->order->id,
                            'user_id'=>$record->user_id,
                            'is_complete'=>true
                        ]);
                        $record->delete();
                        \DB::commit();
                        Notification::make('success')->title('نجاح العملية')->body('تم إضافة المبلغ إلى رصيدك')->success()->send();
                    }catch (\Exception | \Error $e){
                        Notification::make('error')->danger()->title('خطأ')->body($e->getMessage())->send();
                        \DB::rollBack();
                    }
                })->label('تأكيد استلام المبلغ')->requiresConfirmation()
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
