<?php

namespace App\Filament\Branch\Resources\CityResource\Pages;

use App\Filament\Branch\Resources\CityResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateCity extends CreateRecord
{
    protected static string $resource = CityResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['is_main']=true;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
