<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\AccountStatmentResource\Pages;
use App\Filament\Admin\Resources\AccountStatmentResource\RelationManagers;
use App\Models\AccountStatment;
use App\Models\Balance;
use App\Models\User;
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Columns\BadgeColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Filament\Forms\Components\Textarea;
use pxlrbt\FilamentExcel\Actions\Tables\ExportAction;
use pxlrbt\FilamentExcel\Actions\Tables\ExportBulkAction;
use pxlrbt\FilamentExcel\Exports\ExcelExport;
use App\Enums\OrderTypeEnum;
use App\Enums\OrderStatusEnum;
use App\Enums\FarType;

class AccountStatmentResource extends Resource implements HasShieldPermissions
{
    protected static ?string $model = Balance::class;
    public static function getPermissionPrefixes(): array
    {
        return [
            'view',
            'view_any',
            'create',
            'update',
            'delete',
            'delete_any',
            'publish'
        ];
    }
    protected static ?string $navigationIcon = 'heroicon-o-table-cells';
    protected static ?string $navigationGroup = 'التقارير';

    //H: changed page label
    protected static ?string $pluralModelLabel = 'كشف حساب';
    protected static ?string $label = 'كشف حساب';
    protected static ?string $navigationLabel = 'كشف حساب';
    public static function canAccess(): bool
    {
        return auth()->user()->hasPermissionTo('view_account::statment');
    }

    public static function canCreate(): bool
    {
        return auth()->user()->hasPermissionTo('view_account::statment'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()->hasPermissionTo('update_account::statment');
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()->hasPermissionTo('delete_account::statment');
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()->hasPermissionTo('delete_account::statment');
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Textarea::make('info')
                ->label('الملاحظات')
                ->columnSpanFull()
                ->visible(fn ($operation): bool => $operation === 'edit') // يظهر فقط في التعديل
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            //  ->poll(10)
            ->columns([
                Tables\Columns\TextColumn::make('id')->label('رقم  الفاتورة')
                ->extraCellAttributes(fn(Model $record) => match ($record->color) {
                    'green' => ['style' => 'background-color:#55FF88;'],
                    'red' =>   ['style' =>'background-color: #FF8888'],
                    null  => ['style'=> ''],
                    default => ['style' => ''],
                }),
                Tables\Columns\TextColumn::make('credit')->label('مدين'),
                Tables\Columns\TextColumn::make('debit')->label('دائن'),
                Tables\Columns\TextColumn::make('currency.code')->label('العملة'),

                /*Tables\Columns\BadgeColumn::make('process_type')
                    ->label('نوع العملية')
                    ->getStateUsing(function ($record) {
                        if ($record->credit == 0) {
                            return 'قبض';
                        } elseif (
                            $record->debit == 0
                        ) {
                            return 'إيداع';
                        }
                        return 'غير معروف';
                    })
                    ->colors([
                        'success' => 'إيداع',
                        'danger' => 'قبض',
                        'gray' => 'غير معروف',
                    ]),*/


                /*Tables\Columns\TextColumn::make('amount')->label('المبلغ')
                    ->getStateUsing(function ($record) {
                        if ($record->credit == 0) {
                            return $record->debit;
                        } elseif ($record->debit == 0) {
                            return $record->credit;
                        }
                        return 'غير معروف';
                    }),*/

                Tables\Columns\TextColumn::make('info')->label('الملاحظات'),
                Tables\Columns\TextColumn::make('customer_name')->label('الطرف المقابل')->searchable(),
                // Tables\Columns\TextColumn::make('order.id')->description(fn($record) => $record->order?->code)->label('الطلب')->searchable(),
                Tables\Columns\TextColumn::make('order.id')
                ->label('الطلب')
                ->getStateUsing(function ($record) {
                    // النص الرئيسي: order.id إذا موجود أو 'N/A' إذا غير موجود
                    return $record->order_id ? $record->order->id : 'N/A';
                })
                ->description(function ($record) {
                    // الوصف: order.code إذا كان هناك order_id، أو balance.code إذا لم يكن
                    if ($record->order_id) {
                        return $record->order?->code ?? 'لا يوجد كود طلب';
                    }
                    return $record->code ?? 'لا يوجد كود رصيد';
                })
                ->copyable()
                ->copyableState(function ($record) {
                    if ($record->order_id) {
                        return $record->order?->code ?? 'لا يوجد كود طلب';
                    }
                    return $record->code ?? 'لا يوجد كود رصيد';
                })
                ->copyMessage('تم نسخ الكود بنجاح')
                ->tooltip('انقر لنسخ الكود')
                ->searchable(),



                Tables\Columns\TextColumn::make('order.sender.name')->label('المرسل')->description(fn($record) => $record->order?->general_sender_name != null ? "{$record->order->general_sender_name}" : "")->searchable(),
                Tables\Columns\TextColumn::make('order.global_name')->label('المستلم'),
                Tables\Columns\TextColumn::make('order.far_sender')
                ->formatStateUsing(fn($state) => FarType::tryFrom($state)?->getLabel())
                ->color(fn($state) => FarType::tryFrom($state)?->getColor())
                ->icon(fn($state) => FarType::tryFrom($state)?->getIcon())
                ->label('حالة الدفع')
                ->description(fn($record) => $record->status?->getLabel())
                ->extraCellAttributes(function ($record) {
                    $list = [];
                    switch ($record->status) {
                        case OrderStatusEnum::PICK:
                            $list = ['style' => 'background-color:yellow'];
                            break;
                        case OrderStatusEnum::TRANSFER:
                            $list = ['style' => 'background-color:orange'];
                            break;
                        case OrderStatusEnum::RETURNED:
                            $list = ['style' => 'background-color:red'];
                            break;
                        case OrderStatusEnum::CANCELED:
                            $list = ['style' => 'background-color:gray;color:black'];
                            break;
                        case OrderStatusEnum::SUCCESS:
                            $list = ['style' => 'background-color:green;color:black'];
                            break;
                    }
                    return $list;
                }),
                Tables\Columns\TextColumn::make('order.status')->label('حالة الطلب'),
                Tables\Columns\TextColumn::make('createdBy.name')->label('أنشئ بواسطة'),
                Tables\Columns\TextColumn::make('order.cityTarget.name')->label('المدينة'),
                Tables\Columns\TextColumn::make('pending')->label('النوع')
                ->formatStateUsing(fn($record) => $record->pending == true ? "قيد التحصيل" : "")->color('danger'),

                //H: disabled the cell
                //Tables\Columns\TextColumn::make('total')->label('الرصيد'),

                //H: get date and time and split them using two temporary columns
                Tables\Columns\TextColumn::make('created_at')->date('Y-m-d')->description(fn($record) => $record->created_at->format('H:i'))
                    ->label('التاريخ والوقت'),

            ])
            ->paginated([10, 25, 50, 100 ,200 , 'all'])
            ->defaultSort('id', 'desc')
            //H: up here, added default sorting to table based on id to show the latest total of an account
            ->filters([
                Tables\Filters\SelectFilter::make('user_id')
                    ->relationship('user', 'name', function ($query) {
                        $query->withCount('balances')
                            ->orderBy('balances_count', 'desc');
                    })
                    ->options(function () {
                        return User::withCount('balances')
                            ->orderBy('balances_count', 'desc')
                            ->take(30)
                            ->pluck('name', 'id');
                    })
                    ->searchable()->default(0)->label('المستخدم')->preload(),


                Tables\Filters\TernaryFilter::make('pending')->trueLabel('قيد التحصيل')->falseLabel('مكتمل')
                    ->queries(
                        true: fn($query) => $query->pending(),
                        false: fn($query) => $query->where('pending', false),
                        blank: fn($query) => $query
                    ),
            ])
            ->headerActions([
                ExportAction::make()->exports([
                    ExcelExport::make()->withChunkSize(100)->fromTable()
                ])
            ])
            ->actions([
                // Tables\Actions\EditAction::make(),
                Tables\Actions\EditAction::make()
                ->form([
                    \Filament\Forms\Components\Textarea::make('info')
                        ->label('الملاحظات')
                        ->columnSpanFull()
                 ]),
                    Tables\Actions\ActionGroup::make([
                      // زر التلوين الأخضر
                    Tables\Actions\Action::make('check_green')
                    ->action(fn($record) => $record->update(['color' => 'green']))
                    ->label('تعيين باللون الاخضر')
                    ->visible(fn($record) => $record->color == null)
                    ->color('success'),

                    // زر التلوين الأحمر

                    Tables\Actions\Action::make('check_red')
                    ->action(fn($record) => $record->update(['color' => 'red']))
                    ->label('تعيين باللون الأحمر')
                    ->visible(fn($record) => $record->color != 'red')
                    ->color('danger'),
                      // زر إزالة التلوين
                    Tables\Actions\Action::make('remove_color')
                    ->action(fn($record) => $record->update(['color' => null]))
                    ->label('إزالة التلوين')
                    ->visible(fn($record) => $record->color != null)
                    ->color('gray')

                    ])

            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    // Tables\Actions\DeleteBulkAction::make(),
             // إجراء تعيين اللون الأخضر جماعيًا
        Tables\Actions\BulkAction::make('bulk_green')
        ->action(fn($records) => $records->each->update(['color' => 'green']))
        ->label('تعيين الأخضر للمحدد')
        ->deselectRecordsAfterCompletion()
        ->color('success')
        ->icon('heroicon-o-check-circle'),

    // إجراء تعيين اللون الأحمر جماعيًا
    Tables\Actions\BulkAction::make('bulk_red')
        ->action(fn($records) => $records->each->update(['color' => 'red']))
        ->label('تعيين الأحمر للمحدد')
        ->deselectRecordsAfterCompletion()
        ->color('danger')
        ->icon('heroicon-o-x-circle'),

    // إجراء إزالة الألوان جماعيًا
    Tables\Actions\BulkAction::make('bulk_remove_color')
        ->action(fn($records) => $records->each->update(['color' => null]))
        ->label('إزالة الألوان')
        ->deselectRecordsAfterCompletion()
        ->color('gray')
        ->icon('heroicon-o-trash'),

            Tables\Actions\DeleteBulkAction::make()
            ->action(function ($records) {
                $recordsToDelete = $records->filter(fn($record) => $record->order_id === null);
                $skippedRecords = $records->count() - $recordsToDelete->count();

                if ($skippedRecords > 0) {
                    Notification::make()
                        ->title('لا يمكن حذف بعض السجلات')
                        ->body("تم تخطي $skippedRecords سجل(ات) لأنها مرتبطة بدفعات")
                        ->warning()
                        ->send();
                }

                $recordsToDelete->each->delete();
            })
            ->deselectRecordsAfterCompletion()
            ->requiresConfirmation()
            ->modalHeading('حذف السجلات المحددة')
            ->modalSubheading(function ($records) {
                $hasLinkedRecords = $records->contains(fn($record) => $record->order_id !== null);
                return $hasLinkedRecords
                    ? 'سيتم تخطي السجلات المرتبطة بدفعات'
                    : 'هل أنت متأكد من أنك تريد حذف هذه السجلات؟';
            })
            ->modalButton('نعم، احذف'),

                    ExportBulkAction::make()->exports([
                        ExcelExport::make()->withChunkSize(300)
                    ])
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAccountStatments::route('/'),
            'create' => Pages\CreateAccountStatment::route('/create'),
            'edit' => Pages\EditAccountStatment::route('/{record}/edit'),
        ];
    }
}
