<?php

namespace App\Filament\Employ\Resources\OrderResource\Pages;

use App\Enums\LevelUserEnum;
use App\Filament\Employ\Resources\OrderResource;
use App\Models\City;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['code'] = "AWB" . now()->format('YmdHis'); // الطابع الزمني بتنسيق قصير
        $data['shipping_date']=now();
        $city_source=City::find($data['city_source_id']);
        $city_target=City::find($data['city_target_id']);

        $data['branch_source_id'] =$city_source->branch_id;
        $data['branch_target_id'] =$city_target->branch_id;
        $target=User::where('level',LevelUserEnum::BRANCH->value)->where('branch_id',$data['branch_target_id'] )->first();
        $data['given_id']=$target?->id;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

}
