<?php

namespace App\Filament\Admin\Pages;




use App\Filament\Admin\Widgets\BalanceCustomerTRWidget;
use App\Filament\Admin\Widgets\BalanceCustomerView;
use App\Filament\Admin\Widgets\BalanceCustomerWidget;
use App\Filament\Admin\Widgets\PendingBalanceCustomerTRYWidget;
use App\Filament\Admin\Widgets\PendingBalanceCustomerWidget;
use Filament\Pages\Page;


class CustomerReport extends Page
{

    protected static ?string $navigationIcon = 'heroicon-o-document-text';
public function getHeaderWidgetsColumns(): int|string|array
{
    return 4; // TODO: Change the autogenerated stub
}

    protected static string $view = 'filament.admin.pages.customer-report';
    protected ?string $heading='أرصدة الزبائن';
    protected static ?string $navigationLabel='أرصدة الزبائن';
    protected static ?string $navigationGroup='التقارير';

    protected function getHeaderWidgets(): array
    {
        return array_merge(parent::getHeaderWidgets(),[
            BalanceCustomerView::class,

            BalanceCustomerWidget::class,
            BalanceCustomerTRWidget::class,
            PendingBalanceCustomerWidget::class,
            PendingBalanceCustomerTRYWidget::class,

        ]); // TODO: Change the autogenerated stub
    }

}
