<?php

namespace App\Filament\Admin\Pages;




use App\Filament\Admin\Widgets\BalanceEmployeeTRWidget;
use App\Filament\Admin\Widgets\BalanceEmployeeView;
use App\Filament\Admin\Widgets\BalanceEmployeeWidget;
use App\Filament\Admin\Widgets\PendingBalanceEmployeeTRYWidget;
use App\Filament\Admin\Widgets\PendingBalanceEmployeeWidget;
use Filament\Pages\Page;

class StaffReport extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.admin.pages.staff-report';
protected ?string $heading='أرصدة الموظفين';
protected static ?string $navigationLabel='أرصدة الموظفين';
protected static ?string $navigationGroup='التقارير';
    public function getHeaderWidgetsColumns(): int|string|array
    {
        return 4; // TODO: Change the autogenerated stub
    }
    protected function getHeaderWidgets(): array
    {
        return array_merge(parent::getHeaderWidgets(),[
            BalanceEmployeeView::class,
            BalanceEmployeeWidget::class,
            BalanceEmployeeTRWidget::class,
            PendingBalanceEmployeeWidget::class,
            PendingBalanceEmployeeTRYWidget::class,

        ]); // TODO: Change the autogenerated stub
    }
}
