<?php

namespace App\Filament\Admin\Resources\RequestExchangeResource\Pages;

use App\Filament\Admin\Resources\RequestExchangeResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateRequestExchange extends CreateRecord
{
    protected static string $resource = RequestExchangeResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id']=auth()->id();
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
