<?php

namespace App\Filament\Admin\Resources\AccountStatmentResource\Pages;

use App\Filament\Admin\Resources\AccountStatmentResource;
use Filament\Actions;
use Filament\Resources\Components\Tab;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use App\Filament\Admin\Resources\AccountStatmentResource\Widgets\AccountStats;
use Filament\Pages\Concerns\ExposesTableToWidgets;
class ListAccountStatments extends ListRecords
{
    use ExposesTableToWidgets;
    protected static string $resource = AccountStatmentResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
    public function getTabs(): array
    {
        return [
            Tab::make('all')->modifyQueryUsing(fn($query)=>$query)->label('الكل'),
            Tab::make('usd')->modifyQueryUsing(fn($query)=>$query->where('currency_id',1))->label('USD'),
            Tab::make('try')->modifyQueryUsing(fn($query)=>$query->where('currency_id',2))->label('TRY'),
        ];
    }
    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->where('is_complete',true)
            ->with(['order'=>fn($query)=>$query->with('sender','receive')])
            ->latest(); // TODO: Change the autogenerated stub
    }

    protected function getHeaderWidgets(): array
{

    return [
        AccountStats::class,
    ];
}
}
