<?php

namespace App\Filament\Admin\Resources\AccountStatmentResource\Pages;

use App\Filament\Admin\Resources\AccountStatmentResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListAccountStatments extends ListRecords
{
    protected static string $resource = AccountStatmentResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->where('pending',false)->where('is_complete',true)
            ->with(['order'=>fn($query)=>$query->with('sender','receive')])
            ->latest(); // TODO: Change the autogenerated stub
    }
}
