<?php

namespace App\Models;

use App\Enums\ActivateAgencyEnum;
use App\Enums\TaskAgencyEnum;
use App\Observers\AgencyObServer;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Agency extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts=[
        'status' => TaskAgencyEnum::class,
        'activate' => ActivateAgencyEnum::class
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(AgencyObServer::class);
    }

    public function order(): BelongsTo
    {
        return $this->belongsTo(Order::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
