<?php

namespace App\Models;

use App\Observers\PackageObServe;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Package extends Model implements HasMedia

{
    use HasFactory, InteractsWithMedia;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(PackageObServe::class);
    }

    public function order(): BelongsTo
    {
        return $this->belongsTo(Order::class);
    }


    public function unit(): BelongsTo
    {
        return $this->belongsTo(Unit::class);
    }

    public function category():BelongsTo

    {

        return $this->belongsTo(Category::class);
    }

}
