<?php

namespace App\Filament\Admin\Resources\OrderResource\Pages;

use App\Enums\LevelUserEnum;
use App\Filament\Admin\Resources\OrderResource;
use App\Models\City;
use App\Models\User;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }


    protected function mutateFormDataBeforeFill(array $data): array
    {
       // $data['sender_name']=User::find($data['receive_id'])?->name;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
 protected function mutateFormDataBeforeSave(array $data): array
 {
     $city_source=City::find($data['city_source_id']);
     $city_target=City::find($data['city_target_id']);
     $data['branch_source_id'] =$city_source->branch_id;
     $data['branch_target_id'] =$city_target->branch_id;
     return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
 }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
