<?php

namespace App\Filament\Branch\Pages;

use App\Models\Balance;
use App\Models\Currency;
use App\Models\User;
use Closure;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Notifications\Notification;
use Filament\Pages\Page;

class ExchangeUser extends Page implements HasForms
{
    use InteractsWithForms;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.admin.pages.exchange-user';
protected static ?string $navigationLabel='تصريف دولار';
    protected static ?string $model = Balance::class;
    protected static ?string $navigationGroup = 'الحسابات المالية';
  protected ?string $heading = 'تصريف دولار';
    protected static ?string $label = 'إنشاء سند';
    protected static ?string $pluralLabel = 'إنشاء سند';
    public static function canAccess(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    public $data = [
        'from' => '',
        'to' => '',
        'value' => '',
        'info' => '',
        'type',
        'price',
    ];

    public function mount(): void
    {
        $this->data['price']=Currency::find(2)->down_value;
        $this->form->fill($this->data);
    }

    public function getFormSchema(): array
    {

        return [

            TextInput::make('price')->label('سعر صرف الدولار بالنسبة للتركي')->required()->readOnly(),

            TextInput::make('value')->numeric()->label('القيمة بالدولار')->rules([
                fn(): Closure => function (string $attribute, $value, Closure $fail) {
                    if ($value <= 0) {
                        $fail('يجب ان تكون القيمة أكبر من 0');
                    }
                },
            ])->required()->live()->dehydrated(false),
            Textarea::make('info')->label('بيانات'),
            Placeholder::make('message')->dehydrated(false)->content(fn($get)=>"سيتم تحويل مبلغ {$get('value')} من صندوق التركي  إلى صندوق الدولار بقيمة ". (float)$get('value')*(float)$get('price'))->label('تحذير')->extraAttributes(['style'=>'color:red']),

        ];
    }


    public function submit()
    {
        $data = $this->form->getState();

        \DB::beginTransaction();
        try {
          $down=  Currency::find(2)->down_value;
                if(auth()->user()->total_balance < $data['value']){
                    throw  new \Exception('لا تملك رصيد كافي');
                }
                Balance::create([
                    'credit' => 0,
                    'debit' => $data['value'],
                    'is_complete' => true,
                    'pending' => false,
                    'user_id' => auth()->id(),
                    'currency_id' => 1,
                    'ex_cur' => $down,
                    'info' => 'تحويل من حساب الدولار إلى حساب التركي #' . ' - ' . $data['info'],
                ]);
                Balance::create([
                    'credit' => $data['value'] * $down,
                    'debit' => 0,
                    'is_complete' => true,
                    'pending' => false,
                    'user_id' => auth()->id(),
                    'currency_id' =>2,
                    'ex_cur' => $down,
                    'info' => 'تحويل من حساب الدولار إلى حساب التركي #' . ' - ' . $data['info'],
                ]);



            \DB::commit();
            Notification::make('success')->success()->title('نجاح العملية')->body('تم التحويل')->send();
        } catch (\Exception | \Error $e) {
            \DB::rollBack();
            Notification::make('error')->danger()->title('فشل العملية')->body($e->getMessage())->send();
        }

    }

    protected function getFormStatePath(): ?string
    {
        return 'data';
    }
}
